apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# istio-system namespace
- ./mainifests/istio-system-ns.yaml

# istio-gateway namespace
- ./mainifests/istio-ingress-ns.yaml

# istio ingress class
- ./mainifests/ingress-class.yaml

# kuberntes gateway resources
- https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml

# service monitor etc.
- https://raw.githubusercontent.com/istio/istio/refs/heads/master/samples/addons/extras/prometheus-operator.yaml

helmCharts:
- name: base
  repo: https://istio-release.storage.googleapis.com/charts
  version: "1.23.2"
  includeCRDs: true
  releaseName: istio-base
  namespace: istio-system
- name: istiod
  repo: https://istio-release.storage.googleapis.com/charts
  version: "1.23.2"
  releaseName: istio-istiod
  valuesFile: values/istiod.yaml
  namespace: istio-system
- name: cni
  repo: https://istio-release.storage.googleapis.com/charts
  version: "1.23.2"
  releaseName: istio-cni
  valuesFile: values/cni.yaml
  namespace: istio-system
- name: ztunnel
  repo: https://istio-release.storage.googleapis.com/charts
  version: "1.23.2"
  releaseName: istio-ztunnel
  valuesFile: values/ztunnel.yaml
  namespace: istio-system
- name: gateway
  repo: https://istio-release.storage.googleapis.com/charts
  version: "1.23.2"
  releaseName: istio-gateway
  valuesFile: values/gateway.yaml
  namespace: istio-ingress

patches:
  # Add tolerations to Deployment resources
  - path: patches/add-tolerations.yaml
    target:
      name: .*
      kind: Deployment

  # Add tolerations to DaemonSet resources
  - path: patches/add-tolerations.yaml
    target:
      name: .*
      kind: DaemonSet

  # Add tolerations to StatefulSet resources
  - path: patches/add-tolerations.yaml
    target:
      name: .*
      kind: StatefulSet