---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: istio-base
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  source:
    chart: base
    repoURL: https://istio-release.storage.googleapis.com/charts/
    targetRevision: 1.13.2
  project: ounu-workload
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-istiod
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  source:
    chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts/
    targetRevision: 1.13.2
  project: ounu-workload
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
spec:
  destination:
    namespace: istio-ingress
    server: https://kubernetes.default.svc
  source:
    chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts/
    targetRevision: 1.13.2
  project: ounu-workload
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
