apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: istio-

resources:
# istio-gateway namespace
- ./mainifests/istio-ingress-ns.yaml
- ./mainifests/istio-system-ns.yaml
- ./mainifests/istio-ns.yaml
      
helmCharts:
- name: base
  repo: https://istio-release.storage.googleapis.com/charts
  version: "1.14.3"
  includeCRDs: true
  releaseName: istio-base
  namespace: istio-system
- name: istiod
  repo: https://istio-release.storage.googleapis.com/charts
  version: "1.14.3"
  releaseName: istio-istiod
  namespace: istio-system
- name: gateway
  repo: https://istio-release.storage.googleapis.com/charts
  version: "1.14.3"
  releaseName: istio-gateway
  namespace: istio-ingress
      
