apiVersion: v1
kind: Secret
metadata:
  name: hetzner-secret
  annotations:
    avp.kubernetes.io/path: "/hosterei/infra"
    avp.kubernetes.io/secret-version: "4"
type: Opaque
data:
  api-key: <hcloudDNSToken>
