---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: prom-stack
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 35.0.3
    helm:
      values: |
        auth:
          strategy: "anonymous"
  project: ounu-mgmt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
