apiVersion: v1
kind: ConfigMap
metadata:
  name: config-istio
  namespace: knative-serving
data:
  knative: >
    local-gateway.knative-serving.knative-local-gateway: "istio-gateway.istio-ingress.svc.cluster.local"

  


