apiVersion: v1
kind: ConfigMap
metadata:
  name: config-network
  namespace: knative-serving
data:
  auto-tls: Enabled
  http-protocol: Redirected

  namespace-wildcard-cert-selector: >-
    {"matchExpressions": [{"key":"networking.knative.dev/enableWildcardCert","operator": "In", "values":["true"]}]}