apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
- name: reflector
  repo: https://emberstack.github.io/helm-charts
  version: "7.0.173"
  includeCRDs: true
  releaseName: reflector
  namespace: reflector

patches:
  # Add tolerations to Deployment resources
  - path: patches/add-tolerations.yaml
    target:
      name: .*
      kind: Deployment