apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "git@github.com/hosterei/tools.git/base/istio-system/"

helmCharts:
  - name: kiali-operator
    repo: https://kiali.org/helm-charts
    version: "1.55"
    releaseName: kiali-operator
    valuesFile: values/kiali.yaml
    namespace: istio-system