apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "https://github.com/hosterei/tools.git/base/istio-system/"

  - "mainifests/ingress.yaml"

helmCharts:
  - name: kiali-operator
    repo: https://kiali.org/helm-charts
    version: "1.55"
    includeCRDs: true
    releaseName: kiali-operator
    valuesFile: values/kiali.yaml
    namespace: istio-system