apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "./manifests/observability-ns.yaml"

  - ./manifests/networking.yaml

helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: "39.8.0"
  includeCRDs: true
  releaseName: kube-prometheus
  namespace: observability

patches:
- target:
    kind: ServiceMonitor
    name: ".*-kube-prometheus-kube-state-metrics\
          |.*-kube-prometheus-operator\
          |.*-kube-prometheus-grafana\
          |.*-kube-prometheus-operated-services"
  path: ./patches/servicemonitors.yaml

- target:
    kind: Service
    name: ".*-prometheus-node-exporter\
          |.*-kube-prometheus-alertmanager\
          |.*-kube-prometheus-coredns\
          |.*-kube-prometheus-prometheus\
          |.*-kube-state-metrics\
          |.*-grafana"
  path: ./patches/services.yaml

- target:
    kind: Job
  path: ./patches/jobs.yaml