apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "./manifests/observability-ns.yaml"

  - ./manifests/networking.yaml
  - ./manifests/ingress.yaml

helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: "65.3.1"
  includeCRDs: true
  valuesFile: values.yaml
  releaseName: kube-prom
  namespace: observability

patches:
- target:
    kind: ServiceMonitor
    name: ".*-kube-prom-kube-state-metrics\
          |.*-kube-prom-operator\
          |.*-kube-prom-grafana\
          |.*-kube-prom-operated-services"
  path: ./patches/servicemonitors.yaml

- target:
    kind: Service
    name: ".*-prometheus-node-exporter\
          |.*-kube-prom-alertmanager\
          |.*-kube-prom-coredns\
          |.*-kube-prom-prometheus\
          |.*-kube-state-metrics\
          |.*-grafana"
  path: ./patches/services.yaml

# argocd serverside apply
- target:
    kind: CustomResourceDefinition
    name: prometheuses.monitoring.coreos.com
  path: ./patches/argocd-serverside-apply.yaml