apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "./manifests/observability-ns.yaml"

  - ./manifests/networking.yaml
  - ./manifests/ingress.yaml
    
    # awsome k8s dashboards
  - https://github.com/dotdc/grafana-dashboards-kubernetes

helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: "65.3.1"
  includeCRDs: true
  valuesFile: values.yaml
  releaseName: kube-prom
  namespace: observability

patches:
- target:
    kind: ServiceMonitor
    name: "kube-prom.*"
  path: ./patches/servicemonitors.yaml

- target:
    kind: Service
    name: "kube-prom.*"
  path: ./patches/services.yaml

# argocd serverside apply
- target:
    kind: CustomResourceDefinition
    name: ".*.monitoring.coreos.com"
  path: ./patches/argocd-serverside-apply.yaml