grafana:
  defaultDashboardsEnabled: false
  adminPassword: "<path:/hosterei/tools/grafana#adminPassword"

  sidecar:
    dashboards:
      enabled: true
      defaultFolderName: "General"
      label: grafana_dashboard
      labelValue: "1"
      folderAnnotation: grafana_folder
      searchNamespace: ALL
      provider:
        foldersFromFilesStructure: true
#  dashboards:
#    IstioControlPlane:
#      gnetID: 7645
#    IstioServiceDashboard:
#      gnetID: 7636
#    IstioWorkloadDashboard:
#      gnetID: 7630
#    IstioMeshDashboard:
#      gnetID: 7639
#    IstioPerformanceDashboard:
#      gnetID: 11829

