apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: knative

namespace: knative-serving

resources:

- https://github.com/knative/serving/releases/download/knative-v1.8.3/serving-core.yaml
- https://github.com/knative/net-istio/releases/download/knative-v1.8.3/net-istio.yaml
- https://github.com/knative/serving/releases/download/knative-v1.8.3/serving-hpa.yaml

- https://github.com/knative/net-certmanager/releases/download/knative-v1.8.3/release.yaml

- ./manifests/istio-peerauthentication.yaml

patches:
  - path: ./patches/istio-gateway.yaml
  - path: ./patches/config-domain.yaml
  - path: ./patches/config-certmanager.yaml
  - path: ./patches/config-network.yaml
  
  - path: ./patches/istio-gateway.yaml
    target:
      kind: Gateway
      group: networking.istio.io