apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: knative

namespace: knative-serving

resources:

- https://github.com/knative/serving/releases/download/knative-v1.10.1/serving-core.yaml
- https://github.com/knative/net-istio/releases/download/knative-v1.10.0/net-istio.yaml
- https://github.com/knative/serving/releases/download/knative-v1.10.1/serving-hpa.yaml

- https://github.com/knative/net-certmanager/releases/download/knative-v1.10.0/release.yaml

- ./manifests/istio-peerauthentication.yaml

patches:
  - path: ./patches/config-istio.yaml
  - path: ./patches/config-domain.yaml
  - path: ./patches/config-certmanager.yaml
  - path: ./patches/config-network.yaml
  
  - path: ./patches/istio-gateway.yaml
    target:
      kind: Gateway
      group: networking.istio.io

  # Add tolerations to Deployment resources
  - path: patches/add-tolerations.yaml
    target:
      name: .*
      kind: Deployment

  # Add tolerations to DaemonSet resources
  - path: patches/add-tolerations.yaml
    target:
      name: .*
      kind: DaemonSet

  # Add tolerations to StatefulSet resources
  - path: patches/add-tolerations.yaml
    target:
      name: .*
      kind: StatefulSet