apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: knative

namespace: knative-serving

resources:
- ./manifests/knative-serving-ns.yaml

- https://github.com/knative/serving/releases/download/knative-v1.6.0/serving-core.yaml
- https://github.com/knative/net-istio/releases/download/knative-v1.6.0/net-istio.yaml
- https://github.com/knative/serving/releases/download/knative-v1.6.0/serving-hpa.yaml

- ./manifests/istio-peerauthentication.yaml

patches:
  - path: ./patches/config-istio.yaml